version: '3.5'

services:
  spring-app:
    build: ./
    ports:
      - '8080:8080'
      - '8085:8080'
    links:
      - income-db

#  adminer:
#    image: adminer
#    ports:
#      - '8020:8020'

  income-db:
    image: mysql:5.7
    restart: always
    command: --init-file /data/application/init.sql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "123312"
#      MYSQL_DATABASE: "IncomeManagement"
    volumes:
      - database-income-app:/var/lib/mysql
      - ./init.sql:/data/application/init.sql

volumes:
  database-income-app:

networks:
  default:
    name: backend-network-income

